version: '2.3'

services:
  mysql-service:
    build: ./volumes/mysql
    container_name: todo-api-mysql
    ports:
      - 3306:3306
    volumes:
      - ./volumes/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=todo
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
    networks:
      - todo-app-network
  app-service:
    container_name: todo-api
    build: .
    ports: 
      - 8081:8081 
    restart: on-failure
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - mysql-service          # Uncomment this when using postgres.
    networks:
      - todo-app-network
networks:
  todo-app-network:
    driver: bridge
    
