version: '2.3'

services:
  mysql-service:
    build: ./volumes/mysql
    container_name: todo-api-mysql
    ports:
      - 3306:3306
    volumes:
      - ./volumes/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=todo
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
    
