CREATE TABLE user (
    id INT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password LONGTEXT NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)